spring:
  application.name: accountservice
  profiles.active: dev

---
spring:
  config.activate.on-profile: dev
  sql.init.mode: always
  datasource:
    url: "jdbc:h2:mem:demodb"
    driverClassName: org.h2.Driver
    username: demo_user
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui
  mvc.pathmatch.matching-strategy: ant-path-matcher

server:
  port: 9900

#debug: true
logging:
  #level.root: DEBUG
  file.path: /var/logs
  file.name: /var/logs/accounts.log

---
spring:
  config.activate.on-profile: prod
  sql.init.mode: never
  datasource:
    url: "jdbc:mysql://localhost/accounts_db"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: account_user
    password: acc123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    defer-datasource-initialization: true


server:
  port: 9943
  servlet.context-path: /api/v1

logging.level.root: error